import Head from 'next/head'
import { ISbStoriesParams, ISbStoryParams, StoryblokComponent, getStoryblokApi, useStoryblokState } from '@storyblok/react'



export default function Home({ story }: any) {
  story = useStoryblokState(story);
  console.log('tha blok',story);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
   
      <StoryblokComponent blok={story?.content} />
    </>
  )
}


export async function getServerSideProps(context: any) {
  // get the query object
  const insideStoryblok = context.query._storyblok;
 
  let slug = "home";
 
  let sbParams :ISbStoryParams = {
    version: "published", // or 'draft'
  };
 
  if (insideStoryblok) {
    sbParams.version = "draft";
  }
 
  const storyblokApi = getStoryblokApi();
  let { data } = await storyblokApi.get(`cdn/stories/${slug}`, sbParams);
 
  return {
    props: {
      story: data ? data.story : false,
      key: data ? data.story.id : false,
    },
  };
}
